// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rps.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Medal int32

const (
	Medal_Essene Medal = 0
	Medal_Gold   Medal = 1
	Medal_Charm  Medal = 2
)

var Medal_name = map[int32]string{
	0: "Essene",
	1: "Gold",
	2: "Charm",
}

var Medal_value = map[string]int32{
	"Essene": 0,
	"Gold":   1,
	"Charm":  2,
}

func (x Medal) String() string {
	return proto.EnumName(Medal_name, int32(x))
}

func (Medal) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c843b1340611b64d, []int{0}
}

type Player struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lives                int64           `protobuf:"varint,2,opt,name=lives,proto3" json:"lives,omitempty"`
	Medals               map[int32]Medal `protobuf:"bytes,3,rep,name=medals,proto3" json:"medals,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=proto.Medal"`
	Wins                 Medal           `protobuf:"varint,4,opt,name=wins,proto3,enum=proto.Medal" json:"wins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_c843b1340611b64d, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetLives() int64 {
	if m != nil {
		return m.Lives
	}
	return 0
}

func (m *Player) GetMedals() map[int32]Medal {
	if m != nil {
		return m.Medals
	}
	return nil
}

func (m *Player) GetWins() Medal {
	if m != nil {
		return m.Wins
	}
	return Medal_Essene
}

type Choice struct {
	Chosen               string   `protobuf:"bytes,1,opt,name=chosen,proto3" json:"chosen,omitempty"`
	Player               *Player  `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Choice) Reset()         { *m = Choice{} }
func (m *Choice) String() string { return proto.CompactTextString(m) }
func (*Choice) ProtoMessage()    {}
func (*Choice) Descriptor() ([]byte, []int) {
	return fileDescriptor_c843b1340611b64d, []int{1}
}

func (m *Choice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Choice.Unmarshal(m, b)
}
func (m *Choice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Choice.Marshal(b, m, deterministic)
}
func (m *Choice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Choice.Merge(m, src)
}
func (m *Choice) XXX_Size() int {
	return xxx_messageInfo_Choice.Size(m)
}
func (m *Choice) XXX_DiscardUnknown() {
	xxx_messageInfo_Choice.DiscardUnknown(m)
}

var xxx_messageInfo_Choice proto.InternalMessageInfo

func (m *Choice) GetChosen() string {
	if m != nil {
		return m.Chosen
	}
	return ""
}

func (m *Choice) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type OutCome struct {
	Result               Medal    `protobuf:"varint,1,opt,name=result,proto3,enum=proto.Medal" json:"result,omitempty"`
	Winner               *Player  `protobuf:"bytes,2,opt,name=winner,proto3" json:"winner,omitempty"`
	Looser               *Player  `protobuf:"bytes,3,opt,name=looser,proto3" json:"looser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutCome) Reset()         { *m = OutCome{} }
func (m *OutCome) String() string { return proto.CompactTextString(m) }
func (*OutCome) ProtoMessage()    {}
func (*OutCome) Descriptor() ([]byte, []int) {
	return fileDescriptor_c843b1340611b64d, []int{2}
}

func (m *OutCome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutCome.Unmarshal(m, b)
}
func (m *OutCome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutCome.Marshal(b, m, deterministic)
}
func (m *OutCome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutCome.Merge(m, src)
}
func (m *OutCome) XXX_Size() int {
	return xxx_messageInfo_OutCome.Size(m)
}
func (m *OutCome) XXX_DiscardUnknown() {
	xxx_messageInfo_OutCome.DiscardUnknown(m)
}

var xxx_messageInfo_OutCome proto.InternalMessageInfo

func (m *OutCome) GetResult() Medal {
	if m != nil {
		return m.Result
	}
	return Medal_Essene
}

func (m *OutCome) GetWinner() *Player {
	if m != nil {
		return m.Winner
	}
	return nil
}

func (m *OutCome) GetLooser() *Player {
	if m != nil {
		return m.Looser
	}
	return nil
}

type RPSProto struct {
	Player               []*Player `protobuf:"bytes,1,rep,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RPSProto) Reset()         { *m = RPSProto{} }
func (m *RPSProto) String() string { return proto.CompactTextString(m) }
func (*RPSProto) ProtoMessage()    {}
func (*RPSProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c843b1340611b64d, []int{3}
}

func (m *RPSProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPSProto.Unmarshal(m, b)
}
func (m *RPSProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPSProto.Marshal(b, m, deterministic)
}
func (m *RPSProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPSProto.Merge(m, src)
}
func (m *RPSProto) XXX_Size() int {
	return xxx_messageInfo_RPSProto.Size(m)
}
func (m *RPSProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RPSProto.DiscardUnknown(m)
}

var xxx_messageInfo_RPSProto proto.InternalMessageInfo

func (m *RPSProto) GetPlayer() []*Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Medal", Medal_name, Medal_value)
	proto.RegisterType((*Player)(nil), "proto.Player")
	proto.RegisterMapType((map[int32]Medal)(nil), "proto.Player.MedalsEntry")
	proto.RegisterType((*Choice)(nil), "proto.Choice")
	proto.RegisterType((*OutCome)(nil), "proto.OutCome")
	proto.RegisterType((*RPSProto)(nil), "proto.RPSProto")
}

func init() { proto.RegisterFile("rps.proto", fileDescriptor_c843b1340611b64d) }

var fileDescriptor_c843b1340611b64d = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6a, 0xc2, 0x40,
	0x18, 0x84, 0xbb, 0x26, 0xd9, 0xea, 0x6f, 0x2b, 0xe1, 0xa7, 0x94, 0xd4, 0x53, 0x08, 0x15, 0x42,
	0x0f, 0x82, 0xf1, 0x52, 0x7a, 0x15, 0xf1, 0x54, 0x1a, 0xd6, 0x27, 0x48, 0x75, 0xc1, 0x60, 0x92,
	0x95, 0xdd, 0xa8, 0x78, 0xe8, 0x3b, 0xf6, 0x91, 0x4a, 0xfe, 0x6c, 0x69, 0x2b, 0xf6, 0x94, 0x1d,
	0x66, 0xf6, 0xcb, 0x64, 0x02, 0x3d, 0xbd, 0x33, 0xe3, 0x9d, 0x56, 0xb5, 0x42, 0x8f, 0x1e, 0xd1,
	0x27, 0x03, 0x9e, 0x16, 0xd9, 0x49, 0x6a, 0x44, 0x70, 0xab, 0xac, 0x94, 0x01, 0x0b, 0x59, 0xdc,
	0x13, 0x74, 0xc6, 0x3b, 0xf0, 0x8a, 0xfc, 0x20, 0x4d, 0xd0, 0x09, 0x59, 0xec, 0x88, 0x56, 0xe0,
	0x04, 0x78, 0x29, 0xd7, 0x59, 0x61, 0x02, 0x27, 0x74, 0xe2, 0x7e, 0xf2, 0xd0, 0x32, 0xc7, 0x2d,
	0x68, 0xfc, 0x4a, 0xde, 0xbc, 0xaa, 0xf5, 0x49, 0xd8, 0x20, 0x86, 0xe0, 0x1e, 0xf3, 0xca, 0x04,
	0x6e, 0xc8, 0xe2, 0x41, 0x72, 0x63, 0x2f, 0x50, 0x52, 0x90, 0x33, 0x5c, 0x40, 0xff, 0xd7, 0x45,
	0xf4, 0xc1, 0xd9, 0xca, 0x13, 0x95, 0xf1, 0x44, 0x73, 0xc4, 0x08, 0xbc, 0x43, 0x56, 0xec, 0x25,
	0x75, 0x39, 0x67, 0xb4, 0xd6, 0x4b, 0xe7, 0x99, 0x45, 0x0b, 0xe0, 0xb3, 0x8d, 0xca, 0x57, 0x12,
	0xef, 0x81, 0xaf, 0x36, 0xca, 0xc8, 0xca, 0x7e, 0x93, 0x55, 0x38, 0x02, 0xbe, 0xa3, 0xaa, 0x84,
	0xea, 0x27, 0xb7, 0x7f, 0xfa, 0x0b, 0x6b, 0x46, 0x1f, 0x70, 0xfd, 0xb6, 0xaf, 0x67, 0xaa, 0x94,
	0xf8, 0x08, 0x5c, 0x4b, 0xb3, 0x2f, 0x6a, 0x22, 0x9d, 0xbf, 0xdc, 0x7a, 0x0d, 0xf7, 0x98, 0x57,
	0xd5, 0xbf, 0xdc, 0xd6, 0x6c, 0x62, 0x85, 0x52, 0x46, 0xea, 0xc0, 0xb9, 0x18, 0x6b, 0xcd, 0x68,
	0x02, 0x5d, 0x91, 0x2e, 0x53, 0xfa, 0x5b, 0x3f, 0x8d, 0x19, 0x2d, 0x7e, 0xb9, 0xf1, 0x53, 0x0c,
	0x1e, 0x35, 0x42, 0x00, 0x3e, 0x37, 0x46, 0x56, 0xd2, 0xbf, 0xc2, 0x2e, 0xb8, 0x0b, 0x55, 0xac,
	0x7d, 0x86, 0x3d, 0xf0, 0x66, 0x9b, 0x4c, 0x97, 0x7e, 0x27, 0x99, 0x02, 0x88, 0x74, 0xb9, 0x94,
	0xfa, 0xd0, 0x0c, 0x35, 0x02, 0x57, 0xa8, 0xd5, 0x16, 0xbf, 0xb1, 0xed, 0x7e, 0xc3, 0x81, 0x95,
	0x76, 0x85, 0x77, 0x4e, 0x72, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xb4, 0xb7, 0x48, 0x47,
	0x02, 0x00, 0x00,
}
